export const brands = [
    "Enter the text",
    "Aston Martin",
    "Audi",
    "BMW",
    "Bentley",
    "Buick",
    "Chevrolet",
    "Chrysler",
    "Ford",
    "GMC",
    "HUMMER",
    "Hyundai",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lincoln",
    "Mercedes",
    "MINI",
    "Mitsubishi",
    "Pontiac",
    "Porche",
    "Subaru",
    "Toyota",
    "Volvo",
  ];